### ISSUE TITLE
Fixed header overlaps content (Firefox)

### ISSUE THREAD

**Issue by vrocha** [codefordurham/food-inspector#109]
Content hides behind the fixed top bar when first landing on page. 
![screenshot from 2014-05-06 22 53 33](https://cloud.githubusercontent.com/assets/4960061/2898056/cf83dc8c-d592-11e3-831e-14f7895f08e7.png)

**Comment by specious** [comment]
I can't reproduce it using latest code and any of my Firefoxes.

Here's a FF Nightly screenshot:

![food-inspector-ff-nightly](https://user-images.githubusercontent.com/451178/31161273-dd459fbc-a8a3-11e7-8b74-1aae508f48b1.png)
