### ISSUE TITLE
Add pretty_name field to establishment

### ISSUE THREAD

**Issue by copelco** [codefordurham/food-inspector#111]
Some of the establishment names from the API are slightly incorrect, such as [Chubbys missing an apostrophe](http://ncfoodinspector.com/377/) and [Charlie S with a space between before the letter S](http://ncfoodinspector.com/170/). I think we should add a `blank=True` field to `Establishment` called `pretty_name` that takes precedence if filled in.

This is just something we'd manually edit on the production server's database.

**Comment by JonathanFrederick** [comment]
included in https://github.com/codefordurham/food-inspector/pull/165
