### ISSUE TITLE
Move SSL Cert from StartCom

### ISSUE THREAD

**Issue by JonathanFrederick** [codefordurham/food-inspector#174]
It seems we should move our ssl certificate from StartCom to Let's Encrypt to get Chrome to trust the site.

**Comment by JonathanFrederick** [comment]
@vrocha I'm doing my best to wrap my head around this.  I'm guessing there's changes to be made to our config and I can't just run these [Certbot instructions](https://certbot.eff.org/#ubuntutrusty-nginx).  Can you help point me in the right direction?

**Comment by vrocha** [comment]
@JonathanFrederick This is rather difficult to explain but basically we need to add [this](https://github.com/caktus/margarita/blob/develop/project/web/balancer.sls) file (or a version of it) to our repo inside [this](https://github.com/codefordurham/food-inspector/tree/develop/conf/salt/project/web) directory. After that, follow the instructions here https://caktus.github.io/developer-documentation/margarita/states.html#project-web-balancer.

Getting the balancer.sls file to work with our current version of salt states will be tricky.

**Comment by specious** [comment]
@vrocha, I want to help fix this, but I don't grok the salt stack at all.

**Comment by vrocha** [comment]
@specious If I am not mistaken, I believe, the configuration version that we are using support this https://caktus.github.io/developer-documentation/margarita/states.html#project-web-balancer which means you only need to add this variable to your pillar file:

letsencrypt: true (here https://github.com/codefordurham/food-inspector/blob/develop/conf/pillar/production.sls)

**Comment by specious** [comment]
I'm getting up to speed on the salt stack so I can grok it - https://youtu.be/z6jUo17iwIA
